# Generated by Django 3.2.7 on 2021-10-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='category',
            new_name='variation_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=True),
        ),
    ]
