# Generated by Django 3.2.7 on 2021-10-09 17:24

from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('objects', products.models.VariationManager()),
            ],
        ),
    ]
