# Generated by Django 3.2.7 on 2021-10-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211007_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'slug')},
        ),
    ]
