# Generated by Django 3.2.7 on 2021-10-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211007_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product_image', to='products.ProductImage'),
        ),
    ]
