# Generated by Django 3.2.7 on 2021-09-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210930_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KidSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Size',
            new_name='AdultSize',
        ),
        migrations.RenameField(
            model_name='adultsize',
            old_name='sizes',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='has_adult_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='has_belt_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_kid_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='products.KidSize'),
        ),
    ]
