# Generated by Django 3.2.7 on 2021-09-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210930_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='products.BeltSize'),
        ),
    ]
