# Generated by Django 3.2.7 on 2021-09-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdultSize',
        ),
        migrations.DeleteModel(
            name='KidSize',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='BeltSize',
        ),
    ]
