# Generated by Django 3.2.7 on 2021-10-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211001_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
    ]
